"""
Structured Q4 mesh generator for Cook's membrane.

Geometry:

    upper-left  (0, 44) ----------- (48, 60) upper-right
                     \               |
                      \              |
                       \             |
                        \            |
    lower-left  (0, 0) ------------ (48, 44) lower-right

The mesh is generated by mapping a structured unit-square
grid into the Cook quadrilateral.
"""

import numpy as np


# ============================================================
# Cook's membrane Q4 mesh
# ============================================================

def generate_cooks_q4_mesh(
    nx,
    ny,
):
    """
    Generate a structured Q4 mesh for Cook's membrane.

    Parameters
    ----------
    nx : int
        Number of elements in the horizontal direction.

    ny : int
        Number of elements between the lower and upper edges.

    Returns
    -------
    Coord : np.ndarray
        Nodal coordinates, shape (NumNodes, 2).

    Connectivity : np.ndarray
        Q4 connectivity using 1-based node numbering.

    Notes
    -----
    Q4 local node ordering:

        4 -------- 3
        |          |
        |          |
        1 -------- 2
    """

    # --------------------------------------------------------
    # Input validation
    # --------------------------------------------------------

    if not isinstance(
        nx,
        int,
    ):
        raise TypeError(
            "nx must be an integer."
        )

    if not isinstance(
        ny,
        int,
    ):
        raise TypeError(
            "ny must be an integer."
        )

    if nx < 1:
        raise ValueError(
            "nx must be at least 1."
        )

    if ny < 1:
        raise ValueError(
            "ny must be at least 1."
        )


    # --------------------------------------------------------
    # Geometry
    # --------------------------------------------------------

    x_left = 0.0
    x_right = 48.0

    y_left_bottom = 0.0
    y_left_top = 44.0

    y_right_bottom = 44.0
    y_right_top = 60.0


    # --------------------------------------------------------
    # Generate coordinates
    #
    # s : horizontal reference coordinate, 0 <= s <= 1
    # t : vertical reference coordinate,   0 <= t <= 1
    # --------------------------------------------------------

    Coord = []


    for j in range(
        ny + 1
    ):

        t = (
            j
            / ny
        )


        for i in range(
            nx + 1
        ):

            s = (
                i
                / nx
            )


            # ------------------------------------------------
            # Horizontal coordinate
            # ------------------------------------------------

            x = (
                x_left
                + s
                * (
                    x_right
                    - x_left
                )
            )


            # ------------------------------------------------
            # Lower boundary
            #
            # (0,0) --> (48,44)
            # ------------------------------------------------

            y_bottom = (
                y_left_bottom
                + s
                * (
                    y_right_bottom
                    - y_left_bottom
                )
            )


            # ------------------------------------------------
            # Upper boundary
            #
            # (0,44) --> (48,60)
            # ------------------------------------------------

            y_top = (
                y_left_top
                + s
                * (
                    y_right_top
                    - y_left_top
                )
            )


            # ------------------------------------------------
            # Interpolate between lower and upper boundaries
            # ------------------------------------------------

            y = (
                (1.0 - t)
                * y_bottom
                + t
                * y_top
            )


            Coord.append([
                x,
                y,
            ])


    Coord = np.array(
        Coord,
        dtype=float,
    )


    # --------------------------------------------------------
    # 1-based global node numbering
    # --------------------------------------------------------

    def node_number(
        i,
        j,
    ):

        return (
            j
            * (
                nx + 1
            )
            + i
            + 1
        )


    # --------------------------------------------------------
    # Connectivity
    # --------------------------------------------------------

    Connectivity = []


    for j in range(
        ny
    ):

        for i in range(
            nx
        ):

            n1 = node_number(
                i,
                j,
            )

            n2 = node_number(
                i + 1,
                j,
            )

            n3 = node_number(
                i + 1,
                j + 1,
            )

            n4 = node_number(
                i,
                j + 1,
            )


            Connectivity.append([
                n1,
                n2,
                n3,
                n4,
            ])


    Connectivity = np.array(
        Connectivity,
        dtype=int,
    )


    return (
        Coord,
        Connectivity,
    )